spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: ${DB_CONNECTION_USERNAME:root}
    password: ${DB_CONNECTION_PASSWORD:12345}
    url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:5433}/${DB_NAME:ads_db}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
